name = "kitty/queue"
version = "0.1.0"
description = "queue"
authors = ["kimpure"]
license = "MIT"
includes = [ "src/**", "pesde.toml", "LICENCE.md", "README.md" ]

[target]
environment = "lune"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
greentea_luau = { name = "jiwonz/greentea_luau", version = "^0.1.0", target = "luau" }
task = { name = "jiwonz/task", version = "^0.1.0" }

[dev_dependencies]
darklua = { name = "pesde/darklua", version = "^0.16.0", target = "lune" }
multitarget = { name = "jiwonz/multitarget", version = "^0.2.5", target = "lune" }
